### ISSUE TITLE
Package dependencies refactoring

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/soap-client#2]
https://github.com/radekxrandom/soap-client/blob/25787f8835a6d115e08cb552801d09fc711d6118/package.json#L20

Axios should be in dependencies.

Important to have correctly placed dependencies in package.json file

- dependencies - contains all deps which needed for working your service
- devDependencies - contains all deps which is not required currently for working your site 

In devDependencies should be:
- @types/...
- eslint plugins
- husky
- prettier
- not required packages

**Comment by radekxrandom** [comment]
Can you please open a pull request with your suggestions? I'll merge it immediately.

**Comment by radekxrandom** [comment]
By the way, there are some unused dependencies. I am going to fix this issue but can't find the time. I'd be very grateful should you chose to help with that.

**Comment by radekxrandom** [comment]
Ok, fixed. I had to update axios version anyways because of the security vulnerability that was announced today.
