### ISSUE TITLE
Date formatting function possible refactoring

### ISSUE THREAD

**Issue by v-bondarenko364** [radekxrandom/soap-client#3]
https://github.com/radekxrandom/soap-client/blob/25787f8835a6d115e08cb552801d09fc711d6118/src/soap_xml_helper.js#L7

This function could be refactored using thrid-party package - date-fns
date-fns - a popular library which dealing with dates.

Also another "opponent" for this library - moment.js also date library for js (it you don't like date-fns)

**Comment by radekxrandom** [comment]
Do you think adding another dependency to format date in only one function is justified? 
Open a pull request if you think so. I believe the date should be in the ISO 8601 format. 
https://date-fns.org/v2.16.1/docs/formatISO
This should help you.

**Comment by v-bondarenko364** [comment]
@radekxrandom In current conditions, you could leave as is. I just pointed out that you could use these libraries in your next projects for working with dates.
